spring.application.name=wardroby

spring.main.banner-mode=off
# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/wardroby_db
spring.datasource.username=khan
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
# Optional: Print executed SQL/DDL to the console
spring.jpa.show-sql=true


#security setting
#spring.security.user.name=admin
#spring.security.user.password=123456
#spring.security.user.roles=ADMIN
